management:
  server:
    port: 8082
    base-path: /${spring.application.name}
spring:
  config:
    import: classpath:crypto-rhos-vault-config.yml

jme:
  crypto:
    objectstorage:
      connection:
        access-url: ${jeap.s3.client.endpoint-url}
        access-key: ${jeap.s3.client.access-key}
        secret-key: ${jeap.s3.client.secret-key}
        check-connection-on-startup-required: true

database-migration:
  init-container: ${IS_INIT_CONTAINER_EXECUTION}
  startup-migrate-mode-enabled: false







