spring:
  application:
    name: jme-crypto-vault-service
  config:
    import:
      - "jeap-app-config-aws:"
      - jeap-aws-secretsmanager:jme-crypto-vault-service?prefix=aws.secrets.
  cloud:
    vault:
      enabled: true
management:
  server:
    base-path: ${server.servlet.context-path}
    port: 52873
    ssl:
      enabled: false

jeap:
  vault:
    url: https://dev-vault-rhos.bazg.admin.ch
    authentication: APPROLE
    app-role:
      # The microservice's AppRoleID.
      role-id: "${aws.secrets.app-role-id}"
      # SecretID for authentication with the AppRoleID.
      secret-id: "${aws.secrets.app-role-secret-id}"
  crypto:
    awskms:
      enabled: false
    vault:
      default-secret-engine-path: "transit/${jeap.vault.system-name}"
      default-encryption-key-cache-expiry-duration: 1h # Default applies if not set
      default-decryption-key-cache-expiry-duration: 6h # Default applies if not set
      encryption-key-max-cache-size: 100 # Default applies if not set
      decryption-key-max-cache-size: 50000 # Default applies if not set
      keys:
        gameReviewObjectStore:
          key-name: "jme-crypto-example-s3-key"
          encryption-cache-expiry-duration: 10m # default-encryption-key-cache-expiry-duration applies if not set
          decryption-cache-expiry-duration: 12h # default-decryption-key-cache-expiry-duration applies if not set
        gameDatabase:
          # You can also specify a path for each CryptoService. Here it wouldn't be necessary. For demo purposes only
          secret-engine-path: "transit/jme"
          key-name: "jme-crypto-example-database-key"
        gameReviewMessaging:
          key-name: "jme-crypto-example-messaging-key"
  logging.platform: cloudwatch
  web:
    tls:
      enabled: true
  monitor:
    prometheus:
      secure: false
  postgresql:
    aws:
      enabled: true
  ###
  # Note: In a real environment, it is recommended to get the Kafka configuration properties from AWS AppConfig.
  # The properties are shown here only to provide a complete example.
  # All Kafka properties below are system-wide configuration entries. The service-specific authorization happens
  # via the IAM role assigned to the ECS task, and does not need any specific configuration entries.
  ###
  messaging:
    kafka:
      systemName: jme
      cluster:
        awsMskBazg:
          defaultCluster: true
          bootstrapServers: ${aws.services.kafka.bootstrapServers}
          aws:
            glue:
              registryName: ${aws.services.glue.registryName}
              region: "${aws.services.glue.region}"
              assume-iam-role-arn: "${aws.services.glue.roleArn}"
            msk:
              iamAuthEnabled: true
              region: "${AWS_REGION}"
              assume-iam-role-arn: "${aws.services.kafka.roleArn}"

  datasource:
    hikari:
      # The default RDS IAM authentication token lifetime is 15 minutes, so configure the Hikari DataSource max-lifetime a bit lower to prevent using an invalidated authentication token.
      max-lifetime: 840000
      schema: data
    replica:
      hikari:
        # The default RDS IAM authentication token lifetime is 15 minutes, so configure the Hikari DataSource max-lifetime a bit lower to prevent using an invalidated authentication token.
        max-lifetime: 840000
        schema: data
jme:
  crypto:
    messaging:
      game-review-created-topic-name: jme-crypto-vault-game-review-created
    objectstorage:
      connection:
        check-connection-on-startup-required: true
        region: eu-central-2
        bucket-name: bit-jme-crypto-vault-service-nivel-dev
    test:
      keylocation: "v:transit/jme:jme-crypto-example-database-key"
      
