spring:
  config:
    import: "classpath:crypto-vault-config.yml"
  cloud:
    vault:
      enabled: true
      authentication: TOKEN
      token: secret
  datasource:
    url: "jdbc:postgresql://jme-crypto-db-local:5432/jme-crypto-db-local"
    username: postgres
    password: secret

jme:
  crypto:
    objectstorage:
      connection:
        access-url: http://minio:9000
        access-key: local
        secret-key: localsecret
jeap:
  messaging:
    kafka:
      bootstrapServers: "jme-crypto-broker:29092"
      schemaRegistryUrl: "http://jme-crypto-schema-registry:8081"
      username: user
      password: user-secret
      securityProtocol: SASL_PLAINTEXT
      set-compatibility-mode-none: true
  vault:
    url: http://vault:8200
    authentication: TOKEN
    app-role:
      role-id: 9999-8888-7777
      secret-id: 1234-5678-9012-3456
